### ISSUE TITLE
How the ichimoku values are synced with the candle values?

### ISSUE THREAD

**Issue by ourarash** [rd13/ichimoku#4]
The basic Ichimoku cloud extends to 26 period in the future. Is the last value in the output results vector synced to the last value in the candle vector, or is it synced to the -26th from the right value in the candle the vector? 

In other words, if I want to see if the current price (last item in candle vector) is above/below the cloud, should I use the last item in the result vector, or should I pick the 26th from the right?

**Comment by rd13** [comment]
> if I want to see if the current price (last item in candle vector) is above/below the cloud, should I use the last item in the result vector, or should I pick the 26th from the right?

You would use the last item in the result vector.

The result is not offset, it is calculated up to the current candle. The lagging span which you speak of (26th future candle) is not calculated or included in the results, only the senkou, kijun, and tenkan values for the current candle are returned.

**Comment by ourarash** [comment]
No, I'm not referring to The lagging span, I'm referring to Senku (cloud), with respect to latest price (last candle). Please see the attached pictures, and thanks for the great work.

I believe the last senkou values are the ones that I highlighted at the right of the picture.

![image](https://user-images.githubusercontent.com/20846105/37379945-7aa8522c-26f3-11e8-8d80-64202491b2e7.png)

**Comment by ghost** [comment]
Any chance this can be reopened? It would be very helpful to be able to see this 'future' 26 period cloud as it would help confirm the position taken.

**Comment by buffermet** [comment]
The lagging span is the current closing price.

In order to see if it is above the lagging price action, just compare the current closing price with the highest price of the 26th last candle.

**Comment by buffermet** [comment]
I think this issue is due to the fact that this library returns different values than seen on TradingView, even with the same period configuration.
